site_name: Cognify
site_url: https://kalarp.github.io/cognify/

repo_url: https://github.com/kalarp/cognify
repo_name: kalarp/cognify

theme:
  name: material  # or "mkdocs", "readthedocs", etc.
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - content.code.copy
    - navigation.expand

nav:
  - Home: index.md
  - Project Structure: project_structure.md
  - Getting Started: getting_started.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list

plugins:
  - search

exclude_docs:
  - README.md

